### ISSUE TITLE
find COI sequences

### ISSUE THREAD

**Issue by galicae** [platynereis/resources#2]
two papers from Maria Gambi's lab describe how mitochondrial cytochrome C oxidase subunit I sequences have been gathered. I was not able to find the actual links to the sequence data anywhere; maybe someone with more ecological background could look into this?

**Comment by nrandel** [comment]
Calosi et al 2013:
GenBank: accession numbers KC591782 through KC591950
Amphiglena mediterranea  and Platynereis dumerilii 

Waege et al 2017
**The link in the list is wrong**
GenBank:  accession numbers KT124668 through KT124717
Platynereis dumerilii and Platynerreis sp.

**Comment by nrandel** [comment]
I realized I can edit it by myself. Please feel free to change it.
