### ISSUE TITLE
Culturing Platynereis dumerilii

### ISSUE THREAD

**Issue by BDuyguOzpolat** [platynereis/resources#6]
Publication: 
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226156

Website by Fischer (unfortunately doesn't look like it is available anymore): https://www.uni-giessen.de/static_files/pcms/status/404/404.html

**Comment by platynereis** [comment]
I will create a new wiki page for the culturing discussions/protocols, maybe even add the discussion that was had on the slack channel the other day 🤔 The link however is only for a 404 error, I think - maybe if you could find the original link for me we can use the wayback machine ;)

**Comment by BDuyguOzpolat** [comment]
Ah good point. Here is the actual link: http://www.staff.uni-giessen.de/~gf1307/breeding.htm
Looks like it was saved by the internet archive in Sept 2019, which is not bad.

**Comment by platynereis** [comment]
this worked, I added the text as a file to the repository 👍  I am also finding a description of the [developmental stages](https://web.archive.org/web/20050828105435/http://www.uni-giessen.de/~gf1307/development.htm), but it is not as detailed as [The normal development of Platynereis dumerilii](https://frontiersinzoology.biomedcentral.com/articles/10.1186/1742-9994-7-31), so I am not sure if I should try to rescue it too - do you want to make the call on that?

**Comment by nrandel** [comment]
Would you mind I take the culturing information/ text directly to the website? It might be easier to navigate if we have different version. (Duygu's, Cameron's...)
